spring.application.name=backend
#Database connection
spring.datasource.url = jdbc:postgresql://ep-bold-lake-a8tp62e1-pooler.eastus2.azure.neon.tech/Clothing_Store?staff=neondb_owner&password=npg_Yfv17yOCgJSl&sslmode=require
spring.datasource.username =neondb_owner
spring.datasource.password =npg_Yfv17yOCgJSl

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Json web token
spring.security.jwt.secret =Bpeldari6t9q/KuAxV51EqDxALa9wZtlUYLZ4PhVSig=
spring.security.jwt.expiration =PT24H

#Bat log request
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
#Send Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vuaposerver@gmail.com
spring.mail.password=tjbrzmphcijodila
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
